### ISSUE TITLE
Using su-tunnel under Windows

### ISSUE THREAD

**Issue by Nazz78** [noelwarr/su-tunnel#1]
Hi Noel,

thank you for sharing this very useful tool. Since I am having some problems getting it to work, I kindly ask you for some help.

I've put the .rb files at places specified, but I do not know how to add the actual command to Sublime (I'm NetBeans user, so Sublime is new for me). I've tried to put this:

```
...
{
        "caption": "Send to SU",
        "command": "send_to_su", "args":
        {
           "cmd": ["ruby", "C:/PortableApps/SublimeText2.0.2x64/tunnel_ide.rb", "$file"],
           "file_regex": "^(...*?):([0-9]*):?([0-9]*)"
        }
},
...
```

to my Default.sublime-commands file, but it is not available when I open Tools > Command Pallete... What am I doing wrong? Please help me out :-)

Thanks,
Jernej Vidmar (from Modelur team)

**Comment by Nazz78** [comment]
Hi Noel,

I've created a NetBeans version, but I can not upload it to the repo. Is it because I created new branch (NetBeans)? Do I need some privileges?

Cheers,
Jernej

**Comment by thomthom** [comment]
Jernej, create a fork using GitHub, then push your changes to that. Then from your GitHub fork make a pull request back to Noel's repo. 
See the STL project's readme and wiki for examples of workflow.

**Comment by thomthom** [comment]
I wonder if it would be possible to create Sublime packages, for easy installation... ?

**Comment by Nazz78** [comment]
Hi Thom,

thank you for the tip!

Cheers,
Jernej

**Comment by noelwarr** [comment]
@Jernej  Glad to see you got it working.  I'll look into your fork at a
later date and merge into mine.  The more IDE's the merrier!

@thomthom I looked into making packages for sublime a couple of weeks
back.  It entails forking the sublime package manager, adding it to
that and then making a pull request.  It seemed a little overkill to
me.

2013/10/19 Jernej Vidmar notifications@github.com

**Comment by Nazz78** [comment]
Hi Noel, I just need a bit of help - it's my first time using Git: should I remove my fork and create a new one, or is there a way to pull your recent changes in my exisitng fork?

Cheers,
Jernej

**Comment by noelwarr** [comment]
you can do pretty much anything from the command line but I know that can
be really tricky if you're not used to it.  I suggest deleting your repo on
github and then forking mine.  Switch branches to "pr/2" and you'll find
all the changes you made plus some I made too.  That should make the
workflow much more natural simply because github will know yours is a fork
of mine.

2013/10/22 Jernej Vidmar notifications@github.com

**Comment by noelwarr** [comment]
Just merged the netbeans branch into master.  Am closing this issue.  Thanks Nazz!
