### ISSUE TITLE
SKETCHUP_CONSOLE(...)

### ISSUE THREAD

**Issue by jimfoltz** [noelwarr/su-tunnel#8]
Not sure I understand this (see link) use of SKETCHUP_CONSOLE constant?

```
SKETCHUP_CONSOLE(self.log.join)
```

SKETCHUP_CONSOLE is not a method, but a Constant pointing at the Sketchup::Console instance.

https://github.com/noelwarr/su-tunnel/blob/master/tunnel_skp.rb#L54

EDIT - Oh, is there supposed to be a `.write` method in there?

**Comment by noelwarr** [comment]
Its late.  I'll try and get back to you either tomorow or monday.  This
would be easily explained over a beer. :)

**Comment by noelwarr** [comment]
I was going to explain about replacing $stdout with your own streaming
object but to be honest I don't know what that is but it obviously isn't
right.  Ok.  A couple of things:

1)  Last time I checked the tunnel was working but I assume its not working
for you since that line really doesn't make any sense and you've emailed me
about it.  When things work people usually don't look into code.

2)  About 4 months ago I switched platforms (on mac now) and the tunnel
wouldn't work on mac because SKSockets behave slightly differently.  I
changed my approach and now use a file to communicate between the IDE and
SU.  I just tried it on PC this weekend and it seems to work fine.  Have
yet to commit my changes yet.  Must find a moment.  Please find the new
file attached.

There used to be two files.  Now there is only one.  Pop it in your plugins
folder and then tell your IDE to execute...
ruby path_to_plugins/su-tunnel.rb my_file.rb
I'm not sure why I've refactored into one file.  Thought it might make
users lives easier.

**Comment by noelwarr** [comment]
Just committed my changes.  You'll have a tad more work pointing your IDE to the su-tunnel file but I think having the one file makes the user's life a little easier

There is some Python stuff I use for my work with V-Ray around line 122.  You can just ignore that.  Let me know if it works.  :)

**Comment by jimfoltz** [comment]
Thanks for taking the time to explain. Let me try the single-file solution and let you know.  I am all for simpler solutions - and by that I mean simpler to set-up, simpler to use,  and simpler to debug.

**Comment by noelwarr** [comment]
simpler to setup:  an installer would be nice, wouldn't it.  For sublime
you are now required to edit the Sketchup.sublime-build.  Are you using
sublime or some other ide?
simpler to use:  as simple as always :)  No change there
simpler to debug.  Mixing the two files might have been a bad choice in
this sense.  The file checks if Sketchup is defined to find out if it is
being run by Sketchup or the IDE.  It'll do different things depending on
each case.  It's certainly an unorthodox approach.

**Comment by jimfoltz** [comment]
i am trying Sublime for the 3rd time. I've been using the same editor (vim) for many, many years but I see many of the things I like about vim in sublime but with a better design. Dropping old habits is proving difficult, but sublime is fantastic. Also I am sort-of afraid to upgrade vim because i have put so many hours into getting it behave the way I like, and I don't want to go through it again. This doesn't seem like an issue with sublime.

So the single-file works well. It's a clever solution; but also atypical. For me having a single file adds an additional layer of context I need to think about when reading the code. 

I want to investigate using named-pipes for communication. i don't know much about them at the moment, but from what I do know they seem like a good way for the editor to talk to SketchUp.

Thanks for putting this together.

**Comment by noelwarr** [comment]
No worries Jim.

Knowing you're using it gives me a little ego boost.  Remember, if you want
to stick to vim, the tunnel should be easy to set up on it too.  It's just
a system command after all.  Can't you just use your setup files on the
upgraded vim?  I know I ported my setup from sublime 2 to sublime 3 with
very little hastle.  If I could chose to automatically know how to use an
editor I would either go with vim or emacs.  But sublime is easier for me
to get into.

Incase you plan to develop on Win and OSX or work on a laptop and desktop,
you might want to take a look at this (
http://misfoc.us/post/18018400006/syncing-sublime-text-2-settings-via-dropbox).
 That's how I've setup sublime, and it make my life SO much easier.  I also
have a plugins folder on Dropbox and just point sketchup to it.  That way I
have the same plugins on all my platforms.  Great stuff.

Also, I wanted to say thanks for the webconsole.  Its what I used until I
found the Bridge.  The bridge wouldn't go down with a bugsplat, but I
missed the feedback and is what pushed me to write the tunnel.

It might be a good idea to tear the tunnel into two scripts again.  Feel
free to toy around and send me pull requests.  Just leave the python stuff
in there please.  The named pipes sound good but I thought that was unix
only?  Maybe I'm wrong.  It all provides the same functionality, but I have
to admit it would make me feel warm and fuzzy inside if we were using
pipes. :)

**Comment by thomthom** [comment]
I was a long time Notepad++ user and I kept it along for a while when I was exploring Sublime. Now I've dropped Notepad++ all together. What really helps is watching them tips and tricks on the website. There is so much power in this editor that you don't immediately notice. Also keep an eye on their twitter channel as they announce lots of useful plugins.

**Comment by thomthom** [comment]
@noelwarr : how about setting up pipes via a Ruby C Extension instead of using that undocumented SKSocket class?

**Comment by noelwarr** [comment]
Sounds cool.  The only thing is that it adds no functionally.  We would
have to compile it for windows and mac everytime there was a change.  If
you're up for it, be my guest. :)

btw, just looked at Brighter3D.  Looks awsome.  I've been working for chaos
group for a few months now.  Ray tracing galore :)  Did you use SKUI for
the UI?

**Comment by thomthom** [comment]
Huh? SKUI what where who?

**Comment by noelwarr** [comment]
It's kind of a WebDialog interface making your life easier.
TomTom wrote it.
https://github.com/thomthom/SKUI
